FROM mcr.microsoft.com/dotnet/sdk:6.0 as build

COPY . /src/disinviter

WORKDIR /src/disinviter

RUN dotnet publish --configuration Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0

WORKDIR /app
COPY --from=build /src/disinviter/out ./

EXPOSE 80
ENTRYPOINT ["dotnet", "disinviter.dll"]
